// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkiEOnBgNNfruCxMOZMQIgcISZat0G9ek',
    appId: '1:187000331984:web:d592ad7e90e7e6855fc8d5',
    messagingSenderId: '187000331984',
    projectId: 'chat-application-7a05d',
    authDomain: 'chat-application-7a05d.firebaseapp.com',
    storageBucket: 'chat-application-7a05d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHLLk_HCMGX8acFMNCo6M2S2L4i_fdJ_w',
    appId: '1:187000331984:android:7b11c7eaad74a3925fc8d5',
    messagingSenderId: '187000331984',
    projectId: 'chat-application-7a05d',
    storageBucket: 'chat-application-7a05d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOAlHCLB4jljxqAfRuMFyLEAU-UpvZZrQ',
    appId: '1:187000331984:ios:cfb3bb466a93ab9a5fc8d5',
    messagingSenderId: '187000331984',
    projectId: 'chat-application-7a05d',
    storageBucket: 'chat-application-7a05d.firebasestorage.app',
    iosBundleId: 'com.example.chatApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOAlHCLB4jljxqAfRuMFyLEAU-UpvZZrQ',
    appId: '1:187000331984:ios:cfb3bb466a93ab9a5fc8d5',
    messagingSenderId: '187000331984',
    projectId: 'chat-application-7a05d',
    storageBucket: 'chat-application-7a05d.firebasestorage.app',
    iosBundleId: 'com.example.chatApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkiEOnBgNNfruCxMOZMQIgcISZat0G9ek',
    appId: '1:187000331984:web:4aa385ff743853375fc8d5',
    messagingSenderId: '187000331984',
    projectId: 'chat-application-7a05d',
    authDomain: 'chat-application-7a05d.firebaseapp.com',
    storageBucket: 'chat-application-7a05d.firebasestorage.app',
  );
}
